/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --env-interface AuthEnv` (hash: b86e1b054311b4aae5fa3a1c8735eb11)
declare namespace Cloudflare {
	interface Env {
		DB_AUTH: D1Database;
	}
}
interface AuthEnv extends Cloudflare.Env {}
