/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --env-interface AuthEnv` (hash: 5e49d087e5eb8b353b15576ee8adfe91)
declare namespace Cloudflare {
	interface Env {
	}
}
interface AuthEnv extends Cloudflare.Env {}
