/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --env-interface GatewayEnv` (hash: 3438d51b11b1c9fccd82f7c4835920b3)
declare namespace Cloudflare {
	interface Env {
		AUTH_SERVICE: Fetcher;
	}
}
interface GatewayEnv extends Cloudflare.Env {}
